name= input("Name : ")
email= input("email : ")
jabatan= input("jabatan : ")
age= input("umur : ")
print ("===============")
print ("Name : ",name)
print ("email : ",email)
print ("jabatan :",jabatan)
print ("umur : ",age)